### ISSUE TITLE
Add automation to create new sprint boards and populate with initial notes (backlog link, filters, etc).

### ISSUE THREAD

**Issue by larsks** [CCI-MOC/sprint-tools#1]
It is helpful to have some common notes available on a new sprint board, such as:

- A link to the main backlog
- Filter shortcuts (e.g., "show issues that need help")
- Etc.

**Comment by larsks** [comment]
Also a "sprint notes" note. Probably just use the name of the sprint board plus " notes".

**Comment by larsks** [comment]
I think there may be no api support for setting automation on project columns...so we can create a new board and populate it with columns, but the automation may need to be configured manually.

**Comment by knikolla** [comment]
I'm assuming this was closed by mistake since you linked to it in a PR and GitHub tried to be too smart.

> I think there may be no api support for setting automation on project columns...so we can create a new board and populate it with columns, but the automation may need to be configured manually.

Yes, I don't see anything on the API that points towards that feature being exposed.

**Comment by larsks** [comment]
> I'm assuming this was closed by mistake 

I think it's because the commit in #7 had the words "resolve #1" in it.
