### ISSUE TITLE
Update new sprint board automation to create 24 hours before sprint planning

### ISSUE THREAD

**Issue by msdisme** [CCI-MOC/sprint-tools#30]
Currently, the automation runs the morning of our sprint planning meeting (every 2 weeks on Wed at 10 am). We would like this to be created 24 hours before so that we may move items over sooner.

**Comment by hakasapl** [comment]
Created PR https://github.com/CCI-MOC/sprint-tools/pull/32

**Comment by hakasapl** [comment]
This is no longer relevant due to the switch to ZenHub

**Comment by joachimweyl** [comment]
ZenHub automates this for us.
